// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookStoreAPI.Models;

public partial class Book
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Isbn { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int? Stock { get; set; }

    public DateOnly? PublishDate { get; set; }

    public string Image { get; set; }

    public int? CategoryId { get; set; }

    public int? PublisherId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<FavoriteBook> FavoriteBooks { get; set; } = new List<FavoriteBook>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Publisher Publisher { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Author> Authors { get; set; } = new List<Author>();

    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();
}