// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookStoreAPI.Models;

public partial class Book
{
    public int BookId { get; set; }

    public string Title { get; set; }

    public string Author { get; set; }

    public int? GenreId { get; set; }

    public decimal Price { get; set; }

    public int Stock { get; set; }

    public string Description { get; set; }

    public DateOnly? PublishedDate { get; set; }

    public string CoverImage { get; set; }

    public virtual ICollection<ComboBook> ComboBooks { get; set; } = new List<ComboBook>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual Genre Genre { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}