// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookStoreAPI.Models;

public partial class Combo
{
    public int ComboId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal? TotalPrice { get; set; }

    public decimal? DiscountPrice { get; set; }

    public string Image { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual ICollection<ComboBook> ComboBooks { get; set; } = new List<ComboBook>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}