// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookStoreAPI.Models;

public partial class ComboBook
{
    public int ComboId { get; set; }

    public int BookId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual Book Book { get; set; }

    public virtual Combo Combo { get; set; }
}