// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookStoreAPI.Models;

public partial class Customer
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public string PasswordHash { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string District { get; set; }

    public string Ward { get; set; }

    public string SpecificAddress { get; set; }

    public string Address { get; set; }

    public virtual ICollection<FavoriteBook> FavoriteBooks { get; set; } = new List<FavoriteBook>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}