// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookStoreAPI.Models;

public partial class Favorite
{
    public int FavoriteId { get; set; }

    public int? UserId { get; set; }

    public int? BookId { get; set; }

    public DateTime? AddedDate { get; set; }

    public virtual Book Book { get; set; }

    public virtual User User { get; set; }
}