// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookStoreAPI.Models;

public partial class FavoriteBook
{
    public int CustomerId { get; set; }

    public int BookId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Book Book { get; set; }

    public virtual Customer Customer { get; set; }
}