// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookStoreAPI.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int? UserId { get; set; }

    public int? ShippingAddressId { get; set; }

    public DateTime? OrderDate { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public bool? IsPaid { get; set; }

    public int? VoucherId { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ShippingAddress ShippingAddress { get; set; }

    public virtual User User { get; set; }

    public virtual Voucher Voucher { get; set; }
}