// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookStoreAPI.Models;

public partial class OrderItem
{
    public int OrderItemId { get; set; }

    public int? OrderId { get; set; }

    public int? BookId { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public int? ComboId { get; set; }

    public virtual Book Book { get; set; }

    public virtual Combo Combo { get; set; }

    public virtual Order Order { get; set; }
}