// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookStoreAPI.Models;

public partial class Voucher
{
    public int VoucherId { get; set; }

    public string Code { get; set; }

    public int? DiscountPercent { get; set; }

    public decimal? MaxDiscount { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public decimal? MinOrderAmount { get; set; }

    public int? UsageLimit { get; set; }

    public int? UsedCount { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}